language: python
sudo: false

services:
  - mongodb

matrix:
  include:
    - python: 2.7
    - python: 3.4.3
    - python: 3.5

before_install:
  # use latest because why not?
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  # Set up config for MDS and FS.
  - export MDS_HOST=localhost
  - export MDS_DATABASE=test
  - export MDS_TIMEZONE=US/Eastern
  - mkdir -p /home/travis/.config/metadatastore
  - 'echo ''port: 27017'' > /home/travis/.config/metadatastore/connection.yml'
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION six numpy pandas h5py coverage jsonschema jinja2 scipy
  - source activate testenv
  # deps needed for metadatastore/filestore
  - conda install -n testenv pyyaml
  # Dependencies not in official conda have been uploaded to binstar orgs.
  - conda config --add channels lightsource2
  - conda install mongoengine tzlocal prettytable boltons pymongo pims tifffile tzlocal
  # install all the pip deps
  - pip install coveralls
  - pip install codecov
  # these next three will be replaced by the following two lines soon once
  # conda-forge is activated on metadatastore, filestore and channelarchiver
  # - conda config --add channels lightsource2-dev
  # - conda install -n testenv metadatastore filestore channelarchiver
  - pip install https://github.com/NSLS-II/metadatastore/zipball/master#egg=metadatastore
  - pip install https://github.com/NSLS-II/filestore/zipball/master#egg=filestore
  - pip install https://github.com/NSLS-II/channelarchiver/zipball/master#egg=channelarchiver
  - python setup.py install


script:
  - python run_tests.py -v

after_success:
  - coveralls
  - codecov
