language: python
sudo: false

services:
  - mongodb

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5

before_install:
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh
  - . ~/scripts/init-metadatastore.sh
  - . ~/scripts/init-filestore.sh

install:
  - conda create -n testenv pip nose python=$TRAVIS_PYTHON_VERSION six numpy pandas h5py coverage jsonschema jinja2 scipy pyyaml mongoengine tzlocal prettytable boltons pymongo pims tifffile tzlocal
  - source activate testenv
  # install all the pip deps
  - pip install coveralls
  - pip install codecov
  - python setup.py install


script:
  - python run_tests.py -v

after_success:
  - coveralls
  - codecov
